-- quadragesimo quarto problema do projeto Euler

import Data.List
{--

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

--}


numPentagonal :: Int -> Int
numPentagonal n = n * (3*n - 1) `div` 2

listaPentas = map numPentagonal [1..]

somaPertence n1 n2 l = elem (n1 + n2) l
subPertence n1 n2 l = elem (n1 - n2) l

listaPentasSomasSubs = [abs(pk - pj) | pj <-listaPentas, pk <-listaPentas, somaPertence pj pk listaPentas && subPertence pj pk listaPentas ]
solucao = head $ sort listaPentasSomasSubs
