-- quadragesimo quarto problema do projeto Euler

import Data.List
import Data.Set
{--

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

--}

numPentagonal :: Int -> Int
numPentagonal n = n * (3*n - 1) `div` 2

listaPentas = Data.List.map numPentagonal [1..5000]

ehPenta n = member n (fromList listaPentas)

listaPentasSomasSubs = [abs(pj - pk) | pj <-listaPentas, pk <- takeWhile (<pj) listaPentas, ehPenta (pj + pk), ehPenta (pj - pk)]
solucao = head listaPentasSomasSubs

main :: IO ()
main = print solucao
