-- quadragesimo quinto problema do projeto Euler

{--

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

--}

-- observacoes: os numeros pentagonais sao um sub conjunto dos numeros triangulares
-- todo numero hexagonal é um numero triangular impar

isInt :: Double -> Bool
isInt x = x == fromInteger (round x)

isPentagonal :: Integer -> Bool
isPentagonal number =
    isInt $ (sqrt (1 + 24 * fromInteger number) + 1) / 6

numeroHexagonal :: Integer -> Integer
-- dadao um numero n retorna o nth numero hexagonal
numeroHexagonal n = n * (2*n - 1)

listaHex :: [Integer]
listaHex = map numeroHexagonal [144..]

--solucao :: Int muito LENTA
--solucao = head [t | t<-listaTris, p<-listaPentas, h<-listaHex, t==p,p==h]

solucao :: Integer
solucao = head [t | t <-listaHex, isPentagonal t]

main :: IO ()
main = print solucao
